from __future__ import annotations

from typing import Any

from .models import Dataset
from .schema import approved, clean, to_int


def generate_optimization_changes(dataset: Dataset) -> list[dict[str, Any]]:
    existing_change_ids = {clean(row.get("change_id")) for row in dataset.tables.get("BulkChanges", [])}
    changes: list[dict[str, Any]] = []
    snapshots = dataset.tables.get("PerformanceSnapshots", [])
    for rule in dataset.tables.get("OptimizationRules", []):
        if not approved(rule.get("approval_status")):
            continue
        matches = [
            snapshot for snapshot in snapshots
            if _snapshot_matches_rule(snapshot, rule)
        ]
        max_actions = to_int(rule.get("max_actions"))
        if max_actions:
            matches = matches[:max_actions]
        for snapshot in matches:
            object_level = clean(rule.get("action_object_level")).lower()
            object_key = _object_key_for_snapshot(snapshot, object_level)
            if not object_key:
                continue
            change_id = _change_id(rule, object_key, existing_change_ids)
            existing_change_ids.add(change_id)
            changes.append(
                {
                    "change_id": change_id,
                    "operation": "SET_FIELD",
                    "object_level": object_level,
                    "object_key_or_meta_id": object_key,
                    "field": clean(rule.get("action_field")),
                    "old_value": "",
                    "new_value": clean(rule.get("action_value")),
                    "value_json": "",
                    "effective_at": "",
                    "reason": f"Generated by optimization rule {clean(rule.get('rule_key'))}",
                    "requested_by": "optimization",
                    "approval_status": "APPROVED",
                    "applied_at": "",
                    "result": "",
                    "error": "",
                }
            )
    return changes


def _snapshot_matches_rule(snapshot: dict[str, Any], rule: dict[str, Any]) -> bool:
    if clean(snapshot.get("object_level")).lower() != clean(rule.get("scope_level")).lower():
        return False
    metric = _float(snapshot.get(clean(rule.get("metric"))))
    threshold = _float(rule.get("threshold"))
    operator = clean(rule.get("operator"))
    if operator == ">":
        return metric > threshold
    if operator == ">=":
        return metric >= threshold
    if operator == "<":
        return metric < threshold
    if operator == "<=":
        return metric <= threshold
    if operator == "==":
        return metric == threshold
    if operator == "!=":
        return metric != threshold
    return False


def _object_key_for_snapshot(snapshot: dict[str, Any], object_level: str) -> str:
    if object_level == "campaign":
        return clean(snapshot.get("campaign_key")) or clean(snapshot.get("meta_object_id"))
    if object_level == "adset":
        return clean(snapshot.get("adset_key")) or clean(snapshot.get("meta_object_id"))
    if object_level == "ad":
        return clean(snapshot.get("ad_key")) or clean(snapshot.get("meta_object_id"))
    return clean(snapshot.get("meta_object_id"))


def _change_id(rule: dict[str, Any], object_key: str, existing: set[str]) -> str:
    prefix = clean(rule.get("generated_change_prefix")) or f"opt_{clean(rule.get('rule_key'))}"
    base = f"{prefix}_{object_key}".replace(" ", "_")
    candidate = base
    idx = 2
    while candidate in existing:
        candidate = f"{base}_{idx}"
        idx += 1
    return candidate


def _float(value: Any) -> float:
    try:
        return float(clean(value))
    except ValueError:
        return 0.0
